version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mysql
      DB_NAME: gestao_estoque
    volumes:
      - ./src:/src
    ports:
      - "5000:5000"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: gestao_estoque
    ports:
      - "3302:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
